import {StyleSheet, Dimensions, Platform} from 'react-native';
import {colors} from '../common/colors';

const {width, height} = Dimensions.get('screen');
export const style = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    margin: 15,
    backgroundColor: 'rgba(98,179,99,0.1)',
    borderColor: colors.lightGreen,
    borderWidth: 1,
  },
  searchContainerView: {flexDirection: 'row', alignItems: 'center'},
  searchContainerImageSearch: {width: 20, height: 20, marginRight: 15},
  searchContainerText: {
    fontSize: 15,
    fontFamily: 'Lato-Regular',
    color: colors.placeholder,
  },
  searchContainerImageMike: {width: 20, height: 20},
  sectionOneScrollview: {
    justifyContent: 'center',
    alignItems: 'center',
    height: width * 0.55,
  },
  sectionOneImgBg: {
    width: width * 0.8,
    height: width * 0.5,
    resizeMode: 'cover',
    borderRadius: 15,
    overflow: 'hidden',
    margin: 15,
    justifyContent: 'center',
  },
  sectionOneHeadtext: {
    fontSize: 20,
    color: 'black',
    fontFamily: 'Lato-Bold',
    marginLeft: 10,
  },
  sectionOnetext: {
    fontSize: 16,
    color: colors.black,
    fontFamily: 'Lato-Regular',
    marginLeft: 10,
  },
  sectionOneTouch: {
    width: width * 0.3,
    borderRadius: 10,
    backgroundColor: colors.primaryGreen,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginLeft: 10,
    marginTop: 10,
  },
  sectionOneTouchText: {
    fontSize: 16,
    color: colors.white,
    fontFamily: 'Lato-Regular',
  },
  sectionTwoView: {
    width: width * 0.925,
    height: width * 0.4,
    borderRadius: 15,
    overflow: 'hidden',
    margin: 15,
    padding: 15,
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(98,179,99,0.1)',
  },
  sectionTwoHeadText: {
    fontSize: 18,
    color: 'black',
    fontFamily: 'Lato-Regular',
  },
  sectionTwoImgView: {
    width: width * 0.15,
    height: width * 0.2,
    borderRadius: 10,
    backgroundColor: colors.white,
    marginVertical: 15,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTwoImg: {width: width * 0.1, height: width * 0.1},
  sectionFourItemView: {
    alignSelf: 'center',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 15,
    padding: 15,
    flexDirection: 'row',
    width: width * 0.9,
    margin: 15,
  },
});
