import {StyleSheet, Dimensions, Platform} from 'react-native';
import {colors} from '../common/colors';

const {width, height} = Dimensions.get('screen');
export const style = StyleSheet.create({
  container: {
    flex: 1,
  },
  trendingProView: {width: width, padding: 15},
  trendingProItemView: {},
  trendingProImgView: {
    borderRightWidth: 1,
    borderRightColor: colors.borderGrey,
    padding: 8,
    paddingRight: 10,
  },
  trendingProImg: {width: width * 0.17, height: width * 0.17},
  coupunEdge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.whitesmoke,
  },
  orderDetailsHeadText: {
    fontFamily: 'Lato-Bold',
    fontSize: 17,
    color: colors.black,
    marginBottom: 10,
  },
  orderDetailsText: {
    fontFamily: 'Lato-Regular',
    fontSize: 15,
    color: colors.placeholder,
    marginBottom: 10,
  },
  flatView: {backgroundColor: colors.whitesmoke},
  scrollView: {
    marginLeft: 10,
    marginBottom: 15,
    borderRadius: 15,
    backgroundColor: colors.white,
  },
  scrollContainerStyle: {
    backgroundColor: colors.white,
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 15,
    width: width * 0.9,
    borderRadius: 15,
  },
  scrollBlock: {width: width * 0.55},
  itemName: {
    fontSize: 15,
    color: 'black',
    fontFamily: 'Lato-Regular',
  },
  itemDesc: {
    fontSize: 14,
    color: 'black',
    fontFamily: 'Lato-Regular',
  },
  priceView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  priceText: {
    fontSize: 15,
    color: 'black',
    fontFamily: 'Lato-Bold',
  },
  discountView: {
    backgroundColor: colors.primaryGreen,
    padding: 5,
    justifyContent: 'center',
    borderRadius: 15,
  },
  discountText: {
    fontSize: 12,
    color: colors.white,
    fontFamily: 'Lato-Regular',
  },
  removeView: {
    borderColor: colors.borderGrey,
    borderWidth: 1,
    padding: 5,
    justifyContent: 'center',
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: width * 0.2,
  },
  removeText: {
    fontSize: 14,
    color: colors.black,
    fontFamily: 'Lato-Black',
    marginTop: -10,
  },
  removeQuantity: {
    fontSize: 16,
    color: colors.primaryGreen,
    fontFamily: 'Lato-Regular',
  },
  removeAdd: {
    fontSize: 14,
    color: colors.black,
    fontFamily: 'Lato-Black',
  },
  deleteTouch: {
    backgroundColor: colors.red,
    marginLeft: 10,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    overflow: 'hidden',
    width: width * 0.2,
  },
  deleteIcon: {width: 25, height: 25, resizeMode: 'cover'},
  emptyView: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    alignSelf: 'center',
  },
  emptyCart: {
    width: width * 0.25,
    height: width * 0.25,
    resizeMode: 'cover',
  },
  emptyText: {
    fontFamily: 'Lato-Bold',
    fontSize: 18,
    color: colors.black,
    textAlign: 'center',
    marginVertical: 10,
  },
  couponView: {
    margin: 15,
    backgroundColor: colors.secondaryGreen,
    width: width * 0.9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    marginBottom: 25,
  },
  totalView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopColor: colors.borderGrey,
    borderTopWidth: 1,
    paddingTop: 15,
    marginVertical: 20,
  },
});
