import {StyleSheet, Dimensions, Platform} from 'react-native';
import {colors} from '../common/colors';

const {width, height} = Dimensions.get('screen');
export const style = StyleSheet.create({
  container: {
    flex: 1,
  },
  trendingProView: {width: width, padding: 15},
  trendingProItemView: {
    alignSelf: 'center',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 15,
    padding: 15,
    flexDirection: 'row',
    width: width * 0.9,
    margin: 15,
  },
  trendingProImgView: {
    borderRightWidth: 1,
    borderRightColor: colors.borderGrey,
    padding: 10,
  },
  trendingProImg: {width: width * 0.17, height: width * 0.17},
  coupunEdge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.whitesmoke,
  },
  orderDetailsHeadText: {
    fontFamily: 'Lato-Bold',
    fontSize: 17,
    color: colors.black,
    marginBottom: 10,
  },
  orderDetailsText: {
    fontFamily: 'Lato-Regular',
    fontSize: 15,
    color: colors.placeholder,
    marginBottom: 10,
  },
  activeFilterText: {
    fontFamily: 'Lato-Bold',
    fontSize: 16,
    color: colors.primaryGreen,
    margin: 10,
    paddingBottom: 5,
  },
  inactiveFilterText: {
    fontFamily: 'Lato-Regular',
    fontSize: 15,
    color: colors.black,
    margin: 10,
    paddingBottom: 5,
  },
  searchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 8,
    margin: 5,
    backgroundColor: 'rgba(98,179,99,0.1)',
    borderColor: colors.lightGreen,
    borderWidth: 1,
    width: width * 0.8,
  },
  searchContainerView: {flexDirection: 'row', alignItems: 'center'},
  searchContainerImageSearch: {width: 20, height: 20, marginRight: 15},
  searchContainerText: {
    fontSize: 15,
    fontFamily: 'Lato-Regular',
    color: colors.placeholder,
  },
  searchContainerImageMike: {width: 20, height: 20},
  sectionFourItemView: {
    alignSelf: 'center',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 15,
    padding: 15,
    flexDirection: 'row',
    width: width * 0.9,
    marginBottom: 15,
  },
});
